name: Terraform CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  AWS_REGION: "us-east-1"

jobs:
  terraform:
    name: Terraform Provisioning
    runs-on: ubuntu-latest

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v4

      - name: Terraform 설치
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: AWS 인증 설정
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set Terraform Variables
        run: echo 'AWS_KEY_PAIR_PUBLIC_KEY=${{ secrets.AWS_KEY_PAIR_PUBLIC_KEY }}' >> $GITHUB_ENV

      - name: Terraform 초기화
        run: terraform init

      - name: Terraform 코드 유효성 검사
        run: terraform validate

      - name: Terraform 실행 계획 확인
        run: terraform plan -out=tfplan

      - name: Terraform 적용
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve -var="aws_key_pair_public_key=$AWS_KEY_PAIR_PUBLIC_KEY"
