name: Terraform CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  AWS_REGION: "us-east-1"

jobs:
  terraform:
    name: Terraform Provisioning
    runs-on: ubuntu-latest

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v4

      - name: Terraform 설치
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: AWS 인증 설정
        run: |
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
          echo "[profile default]" > ~/.aws/config
          echo "region=${{ env.AWS_REGION }}" >> ~/.aws/config

      - name: Terraform 초기화
        run: terraform init

      - name: Terraform 코드 유효성 검사
        run: terraform validate

      - name: Terraform 실행 계획 확인
        run: terraform plan -out=tfplan

      - name: Terraform 적용
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve
